services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'cultureamp/sonatype-nancy']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"