#!/bin/bash
set -euo pipefail

# Yet to do:
# - set nancy version
# - add results to build annotation

go_version="${BUILDKITE_PLUGIN_SONATYPE_NANCY_GO_VERSION:-1-alpine}"
#TODO nancy_version
work_dir="${BUILDKITE_PLUGIN_SONATYPE_NANCY_WORKING_DIRECTORY:-.}"

tmp_dep_list="/tmp/golang-nancy-deps.json"
tmp_nancy_output="/tmp/golang-nancy-results.txt"

src_dir="$(realpath "$(pwd)/${work_dir}")"

image_label="${go_version}"
if [[ "${go_version}" != "latest" && "${go_version}" != *"-"* ]]; then
    # use the Alpine image by default, unless a specific base is in the version
    image_label="${go_version}-alpine"
fi

echo "--- :docker: Pulling images"
docker pull sonatypecommunity/nancy:latest
docker pull golang:"${image_label}"

echo "--- :golang: Extracting dependency list"
docker run --rm -it -v "${src_dir}":/app -w /app "golang:${image_label}" go list -json -m all | tee "${tmp_dep_list}"

echo "--- :nancy: Running Nancy"
docker run --rm -i -v "${src_dir}":/app -w /app sonatypecommunity/nancy:latest sleuth < "${tmp_dep_list}" | tee "${tmp_nancy_output}"

